apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: demo-vm
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: demo-vm-ds-rhel
    spec:
      sourceRef:
        kind: DataSource
        name: rhel9
        namespace: openshift-virtualization-os-images
      storage:
        resources: {}
  template:
    spec:
      terminationGracePeriodSeconds: 180
      domain:
        devices:
          rng: {}
        memory:
          guest: 2048M
      volumes:
      - dataVolume:
          name: demo-vm-ds-rhel
        name: demo-vm-ds-rhel
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: rhel
            password: rhel
            chpasswd: { expire: False }
        name: cloudinitdisk
