apiVersion: v1
kind: Namespace
metadata:
  name: openshift-virtualization-os-images
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  name: fedora
  namespace: openshift-virtualization-os-images
spec:
  source:
    pvc:
      name: fedora
      namespace: openshift-virtualization-os-images
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora
  namespace: openshift-virtualization-os-images
spec:
  source:
    registry:
      pullMethod: node
      url: docker://quay.io/containerdisks/fedora:latest
  storage:
    resources:
      requests:
        storage: 30Gi
